In [8]:
import pandas as pd
import requests
import io

In [10]:


# Set parameters
first_date = '2020-3-5' # yyyy-m-d 
param = 'OZONE' # OZONE, BC, NOX, PM25HR
units = {'OZONE': '007', 'BC': '001', 'NOX': '007', 'PM25HR': '001'}
year = '2020'
mon = '3'
day = '27'
basin = 'SFB-San+Francisco+Bay'
rows = {'OZONE': '20', 'BC': '6', 'NOX': '18', 'PM25HR': '17'}
fname = param+'_'+year+'-'+mon+'-'+day

url = 'https://www.arb.ca.gov/aqmis2/display.php?sitelist=All&filefmt=csv&\
fname='+fname+'&datafmt=web&download=y&first_date='+first_date+'&\
param='+param+'&units='+units[param]+'&year='+year+'&report=PICKDATA&mon='+mon+'&day='+day+'&o3area=&o3pa8=&\
county_name=--COUNTY--&latitude=--PART+OF+STATE--&basin='+basin+'&\
order=basin%2Ccounty_name%2Cs.name&ptype=aqd&o3switch=new&hours=all&statistic=&\
qselect=Screened&start_mon=2&start_day=1&submit=All+Sites&rows='+rows[param]

r = requests.post(url)
if r.ok:
    data = r.content.decode('utf8')
    df = pd.read_csv(io.StringIO(data))

units_dict = {'007': 'ppm', '001': 'µg/m3'}

In [12]:
df.columns

Index(['site', 'date', 'start_hour', 'value', 'variable', 'units', 'quality',
       'prelim', 'name '],
      dtype='object')

In [14]:
df.dropna()

,site,date,start_hour,value,variable,units,quality,prelim,name
0,3828,2020-02-01,0.0,0.0007,OZONE,Parts Per Million ( ppm ),0.0,y,Berkeley-Aquatic Park
1,3828,2020-02-01,1.0,0.0006,OZONE,Parts Per Million ( ppm ),0.0,y,Berkeley-Aquatic Park
2,3828,2020-02-01,3.0,0.0005,OZONE,Parts Per Million ( ppm ),0.0,y,Berkeley-Aquatic Park
3,3828,2020-02-01,4.0,0.0005,OZONE,Parts Per Million ( ppm ),0.0,y,Berkeley-Aquatic Park
4,3828,2020-02-01,5.0,0.0003,OZONE,Parts Per Million ( ppm ),0.0,y,Berkeley-Aquatic Park
...,...,...,...,...,...,...,...,...,...
24878,3804,2020-03-27,4.0,0.0016,OZONE,Parts Per Million ( ppm ),0.0,y,Sebastopol-103 Morris Street
24879,3804,2020-03-27,5.0,0.0009,OZONE,Parts Per Million ( ppm ),0.0,y,Sebastopol-103 Morris Street
24880,3804,2020-03-27,6.0,0.0030,OZONE,Parts Per Million ( ppm ),0.0,y,Sebastopol-103 Morris Street
24881,3804,2020-03-27,7.0,0.0090,OZONE,Parts Per Million ( ppm ),0.0,y,Sebastopol-103 Morris Street
24882,3804,2020-03-27,8.0,0.0207,OZONE,Parts Per Million ( ppm ),0.0,y,Sebastopol-103 Morris Street